#!/bin/bash

################################################################################
# Setup Automated Database Backup Cron Jobs
#
# This script sets up cron jobs for automated database backups with:
# - Daily incremental backups at 2 AM
# - Weekly full backups on Sundays at 3 AM
# - Automatic cleanup of old backups
#
# Usage: sudo ./setup-backup-cron.sh
################################################################################

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_SCRIPT="$SCRIPT_DIR/backup-database.sh"
LOG_DIR="/var/log/ologywood"
CRON_FILE="/etc/cron.d/ologywood-backup"
USER="ubuntu"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "This script must be run as root (use sudo)"
    exit 1
fi

# Create log directory
mkdir -p "$LOG_DIR"
chown "$USER:$USER" "$LOG_DIR"
chmod 755 "$LOG_DIR"

# Create cron job file
cat > "$CRON_FILE" << 'EOF'
# Ologywood Database Backup Cron Jobs
# Generated by setup-backup-cron.sh

# Environment variables
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=admin@ologywood.com

# Daily incremental backup at 2 AM
0 2 * * * ubuntu /home/ubuntu/ologywood/scripts/backup-database.sh incremental >> /var/log/ologywood/backup.log 2>&1

# Weekly full backup on Sunday at 3 AM
0 3 * * 0 ubuntu /home/ubuntu/ologywood/scripts/backup-database.sh full >> /var/log/ologywood/backup.log 2>&1

# Backup verification every Monday at 4 AM
0 4 * * 1 ubuntu /home/ubuntu/ologywood/scripts/backup-database.sh stats >> /var/log/ologywood/backup.log 2>&1
EOF

# Set proper permissions
chmod 644 "$CRON_FILE"

echo "✓ Cron jobs configured successfully"
echo ""
echo "Backup Schedule:"
echo "  - Daily incremental backups: 2:00 AM"
echo "  - Weekly full backups: 3:00 AM (Sundays)"
echo "  - Backup verification: 4:00 AM (Mondays)"
echo ""
echo "Log file: /var/log/ologywood/backup.log"
echo "Cron file: $CRON_FILE"
echo ""
echo "To view cron jobs:"
echo "  sudo crontab -l -u ubuntu"
echo ""
echo "To manually test backup:"
echo "  $BACKUP_SCRIPT full"
echo "  $BACKUP_SCRIPT incremental"
