import PDFDocument from 'pdfkit';
import { getDb } from '../db';
import { invoices, bookings, users } from '../../drizzle/schema';
import { eq } from 'drizzle-orm';
import fs from 'fs';
import path from 'path';

export const invoicePdfService = {
  /**
   * Generate invoice PDF for a booking
   */
  async generateInvoicePdf(bookingId: number, invoiceId: number) {
    try {
      const db = await getDb();
      if (!db) throw new Error('Database connection failed');

      // Get invoice data
      const invoiceResults = await db.select().from(invoices).where(eq(invoices.id, invoiceId)).limit(1);
      const invoice = invoiceResults.length > 0 ? invoiceResults[0] : null;

      if (!invoice) {
        throw new Error('Invoice not found');
      }

      // Get booking details
      const bookingResults = await db.select().from(bookings).where(eq(bookings.id, bookingId)).limit(1);
      const booking = bookingResults.length > 0 ? bookingResults[0] : null;

      if (!booking) {
        throw new Error('Booking not found');
      }

      // Get artist profile
      const artistResults = await db.select().from(users).where(eq(users.id, invoice.artistId)).limit(1);
      const artist = artistResults.length > 0 ? artistResults[0] : null;

      // Get venue profile
      const venueResults = await db.select().from(users).where(eq(users.id, invoice.venueId)).limit(1);
      const venue = venueResults.length > 0 ? venueResults[0] : null;

      // Ensure uploads directory exists
      const uploadsDir = path.join(process.cwd(), 'uploads', 'invoices');
      if (!fs.existsSync(uploadsDir)) {
        fs.mkdirSync(uploadsDir, { recursive: true });
      }

      const fileName = `invoice-${invoice.invoiceNumber}.pdf`;
      const filePath = path.join(uploadsDir, fileName);

      // Create PDF document
      const doc = new PDFDocument();
      const stream = fs.createWriteStream(filePath);

      // Pipe document to file
      doc.pipe(stream);

      // Add content to PDF
      doc.fontSize(24).text('INVOICE', { align: 'center' });
      doc.moveDown();

      // Invoice details
      doc.fontSize(12);
      doc.text(`Invoice Number: ${invoice.invoiceNumber}`, 50, doc.y);
      doc.text(`Invoice Date: ${new Date(invoice.createdAt).toLocaleDateString()}`, 250, doc.y - 20);
      doc.text(`Due Date: ${invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : 'Upon Receipt'}`, 450, doc.y - 20);
      doc.moveDown();

      // From/To section
      doc.fontSize(12).text('FROM (Artist):', 50, doc.y);
      doc.fontSize(10).text(artist?.name || 'Artist Name', 50, doc.y);
      doc.text(artist?.email || '', 50, doc.y);

      doc.fontSize(12).text('TO (Venue):', 250, doc.y - 40);
      doc.fontSize(10).text(venue?.name || 'Venue Name', 250, doc.y);
      doc.text(venue?.email || '', 250, doc.y);
      doc.moveDown();

      // Event details
      doc.fontSize(14).text('Event Details', 50, doc.y);
      doc.fontSize(11);
      doc.text(`Event Date: ${new Date(booking.eventDate).toLocaleDateString()}`, 50, doc.y);
      doc.text(`Event Time: ${booking.eventTime || 'TBD'}`, 50, doc.y);
      doc.text(`Event Details: ${booking.eventDetails || 'N/A'}`, 50, doc.y);
      doc.moveDown();

      // Payment breakdown
      doc.fontSize(14).text('Payment Breakdown', 50, doc.y);
      doc.fontSize(11);
      doc.text(`Booking Fee: $${invoice.amount}`, 50, doc.y);
      doc.text(`Platform Fee: -$${invoice.platformFee}`, 50, doc.y);
      doc.fontSize(12).text(`Total: $${invoice.total}`, 50, doc.y, { underline: true });
      doc.moveDown();

      // Notes
      doc.fontSize(12).text('Notes:', 50, doc.y);
      doc.fontSize(10).text(invoice.notes || 'Thank you for your business!', 50, doc.y);
      doc.moveDown();

      // Footer
      doc.fontSize(9).text('This invoice was generated by Ologywood Artist Booking Platform', 50, doc.y, { align: 'center' });

      // Finalize PDF
      doc.end();

      // Return promise that resolves when stream finishes
      return new Promise((resolve, reject) => {
        stream.on('finish', async () => {
          try {
            // Update invoice with PDF URL
            const pdfUrl = `/uploads/invoices/${fileName}`;
            await db
              .update(invoices)
              .set({ pdfUrl })
              .where(eq(invoices.id, invoiceId));

            resolve({
              pdfUrl,
              filePath,
              fileName,
            });
          } catch (error) {
            reject(error);
          }
        });

        stream.on('error', reject);
        doc.on('error', reject);
      });
    } catch (error) {
      console.error('Error generating invoice PDF:', error);
      throw error;
    }
  },

  /**
   * Get invoice PDF
   */
  async getInvoicePdf(invoiceId: number) {
    try {
      const db = await getDb();
      if (!db) throw new Error('Database connection failed');
      const invoiceResults = await db.select().from(invoices).where(eq(invoices.id, invoiceId)).limit(1);
      const invoice = invoiceResults.length > 0 ? invoiceResults[0] : null;

      if (!invoice || !invoice.pdfUrl) {
        throw new Error('Invoice PDF not found');
      }

      return invoice.pdfUrl;
    } catch (error) {
      console.error('Error getting invoice PDF:', error);
      throw error;
    }
  },

  /**
   * Mark invoice as sent
   */
  async markInvoiceAsSent(invoiceId: number) {
    try {
      const db = await getDb();
      if (!db) throw new Error('Database connection failed');
      await db
        .update(invoices)
        .set({
          status: 'sent',
          sentAt: new Date(),
        })
        .where(eq(invoices.id, invoiceId));

      return true;
    } catch (error) {
      console.error('Error marking invoice as sent:', error);
      throw error;
    }
  },

  /**
   * Mark invoice as paid
   */
  async markInvoiceAsPaid(invoiceId: number) {
    try {
      const db = await getDb();
      if (!db) throw new Error('Database connection failed');
      await db
        .update(invoices)
        .set({
          status: 'paid',
          paidAt: new Date(),
        })
        .where(eq(invoices.id, invoiceId));

      return true;
    } catch (error) {
      console.error('Error marking invoice as paid:', error);
      throw error;
    }
  },
};
